server:
  port: 8080

eureka:
  client:
    # 指定Eureka服务端地址
    service-url:
      defaultZone: http://localhost:8088/eureka


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # 配置路由，注意这里是个列表，每一项都包含了很多信息
      routes:
        - id: user-service   # 路由名称,自定义
          # uri: lb://user-service/user  # 路由的地址，lb表示使用负载均衡到微服务，也可以使用http正常转发
          uri: http://localhost:8082/user
          predicates: # 路由规则，断言什么请求会被路由
            - Path=/user/**  # 只要是访问的这个路径，一律都被路由到上面指定的服务

        - id: secretariat-service-goods
          uri: http://localhost:8083/goods
          predicates:
            - Path=/goods/**

        - id: secretariat-service-borrowInfo
          uri: http://localhost:8083/borrowInfo
          predicates:
            - Path=/borrowInfo/**

        - id: secretariat-service-file
          uri: http://localhost:8081/file
          predicates:
            - Path=/file/**