server:
  port: 8083


spring:
  application:
    name: secretariat-service
  datasource:
    url: jdbc:mysql://localhost:3306/office?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678



eureka:
  client:
    # 指定Eureka服务端地址
    service-url:
      defaultZone: http://localhost:8088/eureka
